### PR TITLE
Modified the way slides are hidden, allowing for animated transitions.

### PR DESCRIPTION
**Pull request by freakboy3742**
This change adds a 'remark-fading' class to a slide when it stops being visible. This class keeps the old slide visible for 1000ms, on a lowered z-index, so that new slides can use an animated transition when they appear. By keeping the old content on the screen, it will look like the new slide is sliding in/out over the old content.

Adding animations is also fairly easy; If you add [animate.css](https://github.com/daneden/animate.css) to your stylesheet for your presentation, and add a class definition to your slide markdown:

```
class: animated slideInRight
```

transitions to that slide will be animated.

If you don't use animated transitions, this change has no effect - the faded slide will be visually "behind" the current slide, making it invisible.

### CODE REVIEW

**Comment by kernc** [comment]
So given this wonderful animated feature, how does one apply a default set of classes to all slides with a single line?

**Comment by utdrmac** [comment]
What's the status of this?

**Comment by utdrmac** [comment]
I'm going to repeat this question cause it's relevant to me: how does one apply a default set of classes to all slides with a single line?

**Comment by utdrmac** [comment]
@kernc Figured it out, in a way. If you are using a layout to apply something to all pages, like a footer and header, you can add `class: animated, slideInRight` to the layout and it will apply to all. This makes all slides animate the same way, if that's what you want.

**Pull request merged**
