### PR TITLE
Continued slides are now concatenated syntactically correct. Nested l…

### LINKED ISSUE #453: Continiued slides are not properly merged (line break is missing)
I am in the process of migrating a multitude of slides from reveal.js to remark.js. While I've worked arround most of the issues and accepted that some things are simply not possible because some internal API functions cannot be accessed from the outside, I now encountered an issue where I am at a point at which I could not find a proper solution unless changing the source code of remark.js.

In fact, I think the issue that I refer to is sort of a bug anyhow. Imagine the following markdown file:
```md
- list point1
--
- list point 2
```

Now, what I expect to see for the content of the second slide, after the parsing process, is this:
```md
- list point 1
- list point 2
```

However, what you get is this:
```md
-list point1-list point2
```

So I consulted the source code and saw that the parser indeed ignores both the trailing line break of `list point 1` as well as the trailing line break of the separator `--`. I think this sort of makes sense because in this example I would also not expect to have the trailing line break's parsed

```md
Some text to display on the first slide
---
Some other text to be displayed on the second slide
```

However.. This leads to really messed up markdown files in order to achieve the desired results, especially with nested lists where trailing line spaces ARE parsed! (I think because 4-level space identation is parsed as type "code" and handled differently?!) So for example this works as expected:

```md
- Some list item (level 1)
    - Some list item (level 2)
--
- Some list item (level 1)
```

As a final example: Imagine a list where some items have nested items and some dont. Furthermore, you want each list item in the first level to be displayed on separate slides. What you would expect to write is this:

```md
- List item 1 (level 1)
--
- List item 2 (level 1)
    - List item 3 (level 2)
--
- List item 4 (level 1)
```

Now, this is what you are required to write in order to get the desired behavior:
```md
- List item 1 (level 1)

--
- List item 2 (level 1)
    - List item 3 (level 2)
--
- List item 4 (level 1)
```

Note that there is no line break between the separator and the 3rd item. Doing so would result in the 2nd and 4th list item being wrapped in an unexpected paragraph, thus changing the layout of the slide! Removing the 3rd item would result in the unexpected behavior described above. Now, I hope you see my point.

Unless this behavior is wanted on purpose I propose to change it to a more reasonable behavior by explicitly prepending a line break to a slide when encountering a slide separator of the form `--`.

### PR DESCRIPTION
**Pull request by Coksnuss**
Fixes #453.

It was also necessary to adapt the lexer in order to not missinterpret nested lists as code blocks. For example, consider the following markdown file

```md
- top level list item
    -nested list item
```

The current lexer interprets the nested list item as a code line because the regex matches a new line followed by 4 spaces and a non-newline character. However, this is not correct because code blocks are expected to have an empty line before them (unless it is the start of the document). However, it might be arguable whether whitespaces in the empty line before the code block are allowed. In my PR I did not allowed for them, but if wished I can change that.

### CODE REVIEW

**Comment by Coksnuss** [comment]
Commit a325423 introduces another approach of preserving the line break between a continious line separator (--). Instead of explicitly adding a new line in front of each continiued slide in the parser, the line break is preserved in the lexing process such that it gets recognized as text.

This fixes the following scenario:
````md
- Level 1 list item
    - Level 2 list item 1
--
    - Level 2 list item 2
```

This scenario does not work with the previous approach because the lexer will eventually executed on the string `    - Level 2 list item 2` which is then recognized as line of code. While this would be correct if there was a slide separator `---` this is an unexpected behavior for a fragment separator `--`. Therefore the lexer was adapter to handle slide separators and fragment separators differently by preserving the trailing new line (if any) at the end of any fragment separator.

**Comment by Coksnuss** [comment]
A response would be nice.. Currently working with a fork that has this PR applied..

**Comment by gnab** [comment]
If you resolve the conflict in src/remark/lexer.js it is all good for merging :)

**Comment by gnab** [comment]
I read your comments more closely and resolved the conflict now.

**Comment by jcrben** [comment]
Seems like the build is failing after this PR? https://travis-ci.org/gnab/remark/jobs/327573387

Not sure why - I'm not a maintainer - noticed a key expired error:
> W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755

**Comment by tripu** [comment]
@jcrben: see #502 (I don't think that error about MongoDB is related in any way).

**Pull request merged**
