### PR TITLE
Add Code Of Conduct

### PR DESCRIPTION
**Pull request by ivannieto**
I find this CoC file a "good to have" in the docs. Aside from README or CONTRIBUTING files. There is still a lot of people lacking of some basic rules on how to behave when it comes to work with other people without prejudges.

This document try to establish some foundations for a healthy  and harassment-free community.

### CODE REVIEW

**Comment by tripu** [comment]
I personally find those covenants patronising and unnecessary, so -1.

**Comment by ivannieto** [comment]
@tripu 

Patronising? (Remember the world we're living)... and unnecessary why?

I'm facing here two positions when adding CoC to some repos. Those who gratefully accept this file with a smile, and those who reject it like it was some kind of evil file. 

I'm now more interested in opinions about it than the merging itself. So I kindly ask you tell me your position in this.

**Comment by tripu** [comment]
@ivannieto:

I think those &ldquo;codes of conduct&rdquo; are mostly unnecessary here because cases of harassment on GitHub are very rare. I admit that I don't have any statistics (I'd love to see them, if someone has some figures), so I may be wrong about this. But based on my own experience of being around for more than five years, my acquaintances' experiences, the GitHub blog, news or posts on web sites and aggregators, etc, I feel that GitHub is very inclusive and tolerant (and even more so by internet standards). Right now, I can't recall any specific instances of harassment, prejudiced discrimination or violent speech that I have witnessed myself here (although I vaguely remember stumbling upon an issue or two where comments became extremely nasty and personal).

Anyone who feels the need to take preemptive action (like discussing and enforcing a code of conduct), should first point at actual instances of the kinds of behaviour they think should be prevented, and prove to others that those cases are something more than very exceptional anecdotes in a community of 14M users and 49M projects. The onus is on the proponents of the code of conduct.

(Specifically, has this project `gnab/remark` ever seen harassment directed towards any of its contributors? I'm curious.)

So if the issue does not exist, or is tiny, I don't think one can justify the overhead and the noise involved in getting (a subset of current) contributors to discuss about and approve on a particular political declaration. (If you happen to think that one code of conduct is &ldquo;neutral&rdquo; and fair and not &ldquo;political&rdquo; in any way, that just means that you agree with that particular code. Believe it or not, others may find it unfair in lots of ways.) There is also the risk of annoying existing contributors or discouraging dissenters from joining, the risk of political bickering that may ensue, the risk of trespassing on subtle cultural differences, etc.

But even if some sort of action were necessary, the kinds of covenants and codes of conduct I'm seeing lately seem childish and patronising to me. They try to make comprehensive lists of areas, behaviours or topics that are to be considered dangerous, potentially offensive, inappropriate, etc. Such list is, by definition, so subject to change, to differences of opinion and to cultural nuances that I am very sceptical about the convenience of trying to put that in writing in the first place. They focus so much on all the possible ways someone might get offended, that they neglect to remind participants about the importance of bona fide humour, irony, playfulness, being responsible, enduring criticism, having a thick skin and embracing the [Principle of Charity](https://en.wikipedia.org/wiki/Principle_of_charity) in order to create [a &ldquo;positive&rdquo; and &ldquo;welcoming&rdquo; environment](http://contributor-covenant.org/version/1/4/).

The best &ldquo;codes&rdquo; I have seen are usually one sentence long: *&ldquo;please, be nice&rdquo;*, or *&ldquo;if you are nasty with others, prepare to face the consequences&rdquo;*, or *&ldquo;everything is tolerated except violent speech and personal attacks; offence is subjective and does not count as a valid argument&rdquo;*. But those align so perfectly with common sense and decency, that there is no point in writing them at all.

**Comment by ivannieto** [comment]
I understand totally your arguments, and I'm really thankful of you taking your time to write them down. 

I like what you say about one line CoC's but I feel they are marking a really wide field for something like "maintainers can do wathever they want if they don't like what you do".

This kind of covenants are written down as a standard way to PREVENT. It's not about if it has happened in the past, it's about what it could happen some time in the future, stating some guidelines on what is not considered a good behaviour for the project and towards other contributors. 

We see LICENSE files standarized, CONTRIBUTING files standarized, I feel this is a good way to reduce noise in the projects. It's just an opinion.

I agree about to add some lines of how to being a happy, joyful and nice contributor, even before the restricting lines.

And about the file itself, it can be changed to the fits of each project, so it's not really restricting at all. Would you like to propose a one line file or reducing it to some lines? I can agree with that and update it if it fits and it's not a "free pass" for maintainers to do whatever they want.

**Comment by tripu** [comment]
Thank you for your thoughts and for being receptive, @ivannieto.

I'd suggest we hear from others (especially from the maintainer of this project) before we take any actions.

I'll continue contributing to Remark (and to other projects) even if it adopts [Contributor Covenant](https://github.com/ContributorCovenant/contributor_covenant) verbatim, although I don't like it much 🙂

**Comment by ivannieto** [comment]
Ofc, it's not game-changing at all. 😄

**Comment by gnab** [comment]
All contributions and discussion have been conducted using what I consider to be common sense and politeness, so I'm going to turn this one down :/

**Pull request closed without merging**
