### PR TITLE
Create .npmignore — closes #217

### LINKED ISSUE #217: Impossible to use with NPM as the asset manager?
Seems very, very odd to ignore `out` in the `.npmignore` file.  Without that folder, attempting to install any tag using NPM will result in a completely unusable folder full of source files.

Would you consider removing the out folder?

### PR DESCRIPTION
**Pull request by chadrien**
`node_modules` and `*.swp` are [automatically handled by `.npmignore`](https://docs.npmjs.com/misc/developers), `out` needs to stay, so the file should only contain `vendor`

### CODE REVIEW

**Comment by chadrien** [comment]
Seem to be working. I've create a "fake" v0.13.0 release on my fork

```bash
$ npm i -S "remark@chadrien/remark#v0.13.0"
$ ls node_modules/remark/out
remark.js     remark.min.js tests.js
```

**Comment by chadrien** [comment]
:tada: 

Do you have any planned release to know when we will be able to use remark with npm?

**Comment by gnab** [comment]
@chadrien I'll try to have a new release out tonight (as in UTC+1 tonight ;)

**Comment by chadrien** [comment]
Yay, thanks :smile:

**Comment by gnab** [comment]
Version 0.13 is now out.

**Comment by chadrien** [comment]
Awesome, I can confirm that remark is now also useable with npm :trophy:

**Pull request merged**
